baseurl = "https://example.com/"
title = "Google Cloud Platform User Group Singapore"
languageCode = "en-us"
defaultContentLanguage = "en"

# Pagination
paginate = 5
paginatePath = "page"

# Theme to use
theme = "hugo-material-blog"

# Copyright, appears in the footer
copyright = "Â© 2018 Copyright Text"

# Links format
[permalinks]
  post = "/:title/"

# English
[languages.en]
  languageName = "English"

  # Main menu
  [[languages.en.menu.main]]
    url = "/"
    name = "Home"
    weight = 1

  # Footer menu 1
  [[languages.en.menu.footer1]]
    url = "#"
    name = "Service 1"
    weight = 1
  [[languages.en.menu.footer1]]
    url = "#"
    name = "Service 2"
    weight = 2

  # Footer menu 2
  [[languages.en.menu.footer2]]
    url = "/"
    name = "Home"
    weight = 1
  [[languages.en.menu.footer2]]
    url = "/about/"
    name = "About"
    weight = 2

  # Include menus in footer
  [[languages.en.params.footer_menus]]
    name = "Services"
    menu = "footer2"
  [[languages.en.params.footer_menus]]
    name = "Links"
    menu = "footer1"

# Other params
[params]
  # Display post summaries instead of content in list templates (default: true)
  # truncate = false